apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: crush-webhook
  namespace: crush
  labels:
    app: crush-webhook
subjects:
  - kind: ServiceAccount
    name: crush-webhook
    namespace: crush
roleRef:
  kind: Role
  name: crush-webhook
  apiGroup: rbac.authorization.k8s.io
