apiVersion: v1
kind: Service
metadata:
  name: crush-webhook
  namespace: crush
  labels:
    app: crush-webhook
spec:
  type: ClusterIP
  selector:
    app: crush-webhook
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
